import React from 'react'
import ReactDOM from 'react-dom'
import './index.css'
import './user.css'
import './components/Contact-page/contact-page.css'
import './components/Home-page/header.css'
import './components/Home-page/footer.css'
import './components/Sign-in page/signIn.css'
import './components/Products-and-cart/products.css'
import './components/Products-and-cart/product-more-info.css'
import './components/Purchases/check-out.css'
import './components/User-page/user-home-page.css'
import { App } from './App'

ReactDOM.render(<App />, document.getElementById('root'))
